python report_edge_features.py edge_features_contact_tape_bert
python report_edge_features.py edge_features_modifications_tape_bert
python report_edge_features.py edge_features_sec_tape_bert
python report_edge_features.py edge_features_sites_tape_bert
python report_edge_features.py edge_features_aa_tape_bert
python report_aa_correlations.py edge_features_aa_tape_bert
python report_edge_features_combined.py --model tape_bert
python report_top_heads.py edge_features_contact_tape_bert
python report_top_heads.py edge_features_sites_tape_bert
python report_top_heads.py edge_features_modifications_tape_bert
